config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get "/home", to: 'static_pages#home'
  get "/service", to:'static_pages#service'
  get "/fee", to:'static_pages#fee'
  get "/staff", to:'static_pages#staff'
  get "/shop", to:'static_pages#shop'
  get "/contact", to:'static_pages#contact'

  get "/signup", to:'users#new'
  get "/users/:id", to: 'users#show'

  get "/login", to:'sessions#new'
  post "/login", to:'sessions#create'
  delete "/logout", to:'sessions#destroy'

  get "/reservations", to: 'reservations#index'
  get "/reservation/new", to: 'reservations#new'
  post "/reservation", to: 'reservations#create'
  get "/reservation/:id", to: 'reservations#show', as: 'reservation_show' # ルート名を変更
  delete "/reservation/:id", to: 'reservations#destroy', as: 'reservation_destroy'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :users
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user

  def self.check_reservation_day(day, time)
    selected_datetime = DateTime.parse("#{day} #{time}")
    current_datetime = DateTime.now
  
    if selected_datetime <= current_datetime
      return "現在時刻か未来の時刻を選択してください。"
    elsif selected_datetime > current_datetime.end_of_day + 2.months
      return "2ヶ月以降の日付は選択できません。"
    end
  end

  def self.reservations_after_three_month
      # 今日から2ヶ月先までのデータを取得
      reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 2).order(day: :desc)
      # 配列を作成し、データを格納
      # DBアクセスを減らすために必要なデータを配列にデータを突っ込んでます
      reservation_data = []
      reservations.each do |reservation|
      reservations_hash = {}
      reservations_hash.merge!(day: reservation.day.strftime("%Y-%m-%d"), time: reservation.time)
      reservation_data.push(reservations_hash)
      end
      reservation_data
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations, dependent: :destroy

    before_save { self.email = email.downcase }
  
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\z/ },
                      uniqueness: true
  
    validates :birth_date, presence: true
    validates :postal_code, presence: true
    validates :address, presence: true
    validates :terms_accepted, acceptance: {accept: true}

  
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    validates :telephone_number, presence: true
    validates :street_number, presence: true
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController


    def index
        @reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 2).order(day: :desc)
    end

    def new
        @reservation = Reservation.new
        @day = params[:day]
        @time = params[:time]
        @start_time = DateTime.parse(@day + " " + @time + " " + "JST")
      
        message = Reservation.check_reservation_day(@day.to_date, @time.to_s)
        if message
          redirect_to @reservation, flash: { alert: message }
        end
    end


    def show 

        case params[:id]
        when 'home', 'service', 'fee', 'staff', 'shop', 'contact', 'reservations'
          redirect_to "/#{params[:id]}" # もしくは特定のパスにリダイレクトしたいページのルートを指定
        else
          # 通常の処理（ユーザー詳細など）を行います
          @reservation = Reservation.find(params[:id])
        end
    end

    def create
        @reservation = Reservation.new(reservation_params)
        if @reservation.save
            redirect_to reservation_show_path(@reservation.id)
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        @reservation = Reservation.find(params[:id])
        
        if @reservation.day > Date.today
          if @reservation.destroy
            flash[:success] = "予約をキャンセルしました"
          else
            flash[:error] = "予約をキャンセルできませんでした"
          end
        else
          flash[:error] = "当日の予約はキャンセルできません"
        end
        
        redirect_to user_path(current_user.id)
    end
      
      
    private
    def reservation_params
        params.require(:reservation).permit(:day, :time, :user_id, :start_time)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:alert_login] = "ログインに失敗しました"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def service
  end

  def fee
  end

  def staff
  end

  def shop
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      redirect_to @user
    else
      flash.now[:alert_index] = "登録に失敗しました"
      render 'new', status: :unprocessable_entity
    end
  end
  

  def show
    @current_user = User.find(current_user.id)
    @user_reservations = current_user.reservations.where("start_time >= ?", DateTime.current).order(day: :desc)

    case params[:id]
    when 'home', 'service', 'fee', 'staff', 'shop', 'contact', 'reservations'
      redirect_to "/#{params[:id]}" # もしくは特定のパスにリダイレクトしたいページのルートを指定
    else
      # 通常の処理（ユーザー詳細など）を行います
      @user = User.find(params[:id])
    end
  end

  

  private
  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :birth_date, 
                                 :postal_code,
                                 :address,
                                 :telephone_number,
                                 :terms_accepted,
                                 :password,
                                 :password_confirmation,
                                 :street_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
    def times
        times = ["1:00",
                 "2:00",
                 "3:00",
                 "4:00",
                 "5:00",
                 "6:00",
                 "7:00",
                 "8:00",
                 "9:00",
                 "10:00",
                 "11:00",
                 "12:00",
                 "13:00",
                 "14:00",
                 "15:00",
                 "16:00",
                 "17:00",
                 "18:00",
                 "19:00",
                 "20:00",
                 "21:00",
                 "22:00",
                 "23:00",
                 "24:00"]
      end

      # 今日から2ヶ月先までの予約データを取得し、特定の形式で配列に格納するメソッド
    #def self.reservations_after_three_months
        #reservations = Reservation.where("day >= ?", Date.current).where("day < ?", Date.current + 2.months).order(day: :desc)
        #reservations.map { |reservation| { day: reservation.day.strftime("%Y-%m-%d"), time: reservation.time } }
    #end
  
    # 予約データに指定した日付と時間が含まれているか確認するメソッド
    def check_reservation(reservations, day, time)
        reservations.any? { |reservation| reservation[:day] == day.strftime("%Y-%m-%d") && reservation[:time] == time }
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if @current_user.nil?
            @current_user = User.find_by(id: session[:user_id])
        else
            @current_user
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        reset_session
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def log_in(user)
        session[:user_id] = user.id
    end
end

app/views/layouts/_footer.html.erb
<footer >
<div class="bg-black text-white">
    <div class="max-w-screen-xl mx-auto py-6">
        <p>住所:〒726-0011 広島県府中市広谷町879-3</p>
        <p>電話番号:080-1648-5870</p>
        <p>E-mail:jo.so.toshi.0208@gmai.com</p>
        <p>公式LINE:@008aqhoo</p>
        <p>Instagram:kishimako.gym</p>
        <p>©kishimako.com</p>
    </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />

<header class="bg-black text-white">
        <div class="max-w-screen-xl mx-auto px-6 py-5 flex justify-between items-center">
            <div>
                <%= image_tag("kishimako.png",id: "icon", class:"rounded-full overflow-hidden w-10 ml-10", alt: "kishimakolog") %>
            </div>
                <nav>
                    <ul class="flex">
                        <% if logged_in? %>
                            <div class="mr-10">
                                <button class="btn" id="btn">
                                アカウント<i id="arrow" class="bx bx-chevron-down"></i>
                                </button>
                                <div id="dropdown" class="dropdown">
                                    <%= link_to " 予約", 'reservations' ,class: "link"%>
                                    <%= link_to " プロフィール", current_user ,class: "link" %>
                                    <%= link_to " ログアウト", logout_path,
                                                                data: { "turbo-method": :delete },
                                                                onclick: "return confirm('本当にログアウトしますか？')",
                                                                class: "link" 
                                    %>
                                </div>
                            </div>
                        <% else %>
                        <li class="ml-auto "><%= link_to "ログイン", 'login', class: "hover:text-gray-300 transition duration-300" %></li>
                        <li class="ml-10 mr-10"><%= link_to "新規登録", 'signup', class: "hover:text-gray-300 transition duration-300" %></li>
                        <% end %>

                        <div class="">
                        <button id="hamburger_js" class="hamburger_button">
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>
                        </div>
                    </ul>
                </nav>
            </div>
    </header>

    <div class="header-second">
        <nav class="text-white bg-gray-600 w-screen py-3 mx-auto">
            <div class="max-w-screen-xl mx-auto px-4"> 
                <ul class="flex justify-between container items-center">
                    <li class="hover:bg-gray-400 transition-all duration-200 flex items-center">
                    <%= link_to "ホーム", 'home',id: "home", class:"text-xl flex items-center justify-center px-6 py-3" %></li>
                    <li class="hover:bg-gray-400 transition-all duration-200 flex items-center">
                    <%= link_to "サービス一覧", 'service', class:"text-xl flex items-center justify-center px-6 py-3" %></li>
                    <li class="hover:bg-gray-400 transition-all duration-200 flex items-center">
                    <%= link_to "料金", 'fee', class:"text-xl flex items-center justify-center px-6 py-3" %></li>
                    <li class="hover:bg-gray-400 transition-all duration-200 flex items-center">
                    <%= link_to "スタッフ紹介", 'staff', class:"text-xl flex items-center justify-center px-6 py-3" %></li>
                    <li class="hover:bg-gray-400 transition-all duration-200 flex items-center">
                    <%= link_to "店舗一覧", 'shop', class:"text-xl flex items-center justify-center px-6 py-3" %></li>
                    <li class="hover:bg-gray-400 transition-all duration-200 flex items-center">
                    <%= link_to "お問い合わせ", 'contact', class:"text-xl flex items-center justify-center px-6 py-3" %></li>
                </ul>
            </div>
        </nav>
    </div>

    <div id="hamburger_div" class="hamburger_div "> 
                <ul class="items">
                    <li class="item">
                    <%= link_to "ホーム", 'home', class:"block w-full h-full" %></li>
                    <li class="">
                    <%= link_to "サービス一覧", 'service', class:"block w-full h-full" %></li>
                    <li class="">
                    <%= link_to "料金", 'fee', class:"block w-full h-full" %></li>
                    <li class="">
                    <%= link_to "スタッフ紹介", 'staff', class:"block w-full h-full" %></li>
                    <li class="">
                    <%= link_to "店舗一覧", 'shop', class:"block w-full h-full" %></li>
                    <li class="">
                    <%= link_to "お問い合わせ", 'contact', class:"block w-full h-full" %></li>
                </ul>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kisimako <%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">

  </head>

  <body>

  <div id="loading">
    <%= image_tag("kishimako.png", class: "spinner") %>
  </div>

    <main id="content" class="spinner2">
      <%= render partial: "layouts/header"%>
      <%= yield %>
      <button id="scroll-to-top-btn">≫</button>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </main>
  </body>
</html>

app/views/reservations/index.html.erb
<% provide(title: "予約一覧")%>

<div class="flex flex-col mb-32">
  <div class="max-w-screen-xl mx-auto mt-8">
    <div class="flex flex-col justify-center items-center">
      <h1 id="mypage-title" class="text-7xl mt-20 mb-20">ー 予約一覧 ー</h1>
      <p class="text-xl mb-5">2ヶ月先まで予約することができます。</p>
    </div>

    <% flash.each do |type, message| %>
        <div class="<%= type %>">
        <%= message %>
        </div>
    <% end %>


    <div class="col-span-12  md:col-span-6 mt-3">
      <%= week_calendar events: @reservations do |date, reservations| %>
        <%= date.day %>
      <% end %>
    </div>

  </div>
</div>

app/views/reservations/new.html.erb
<% provide(title: "新規予約") %>

<div class="flex flex-col mb-32">
  <div class="max-w-screen-xl mx-auto mt-8">
      <h1 id="mypage-title" class="text-7xl mt-20 mb-20">ー 新規予約 ー</h1>

    <div class="flex flex-col justify-center items-center">

      <%= form_with model: @reservation, local: true, class: 'form' do |form| %>
        <div class="day mb-4">
          <%= form.label :day, '日付', class: 'font-bold mb-10' %>
          <%= form.text_field :day, class: 'form-input mt-1 block w-full', value: @day, readonly: true %>
        </div>
        <div class="time mb-4">
          <%= form.label :time, '時間', class: 'font-bold' %>
          <%= form.text_field :time, class: 'form-input mt-1 block w-full', value: @time, readonly: true %>
        </div>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :start_time, value: @start_time %>
        <div class="submit mb-4">
          <%= form.submit value: '予約する', class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
        </div>
      <% end %>
      <div class="text-right">
        <%= link_to '戻る', reservations_path, class: 'text-blue-500 hover:text-blue-700 font-bold' %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<% provide(title: "予約詳細") %>

<div class="flex flex-col mb-32">
  <div class="max-w-screen-xl mx-auto mt-8">
      <h1 id="mypage-title" class="text-7xl mt-20 mb-20">ー 予約詳細 ー</h1>

    <div class="flex flex-col justify-center items-center text-xl mb-2">
      <div class="flex items-center justify-center">
        <label class="font-bold">日付：</label>
        <p class="inline-block ml-2"><%= @reservation.day %></p>
      </div>
      <div class="flex items-center justify-center text-xl mb-10">
        <label class="font-bold">時間：</label>
        <p class="inline-block ml-2"><%= @reservation.time %></p>
      </div>
    </div>
    <div class="text-center text-xl">
      <%= link_to '予約画面に戻る', reservations_path, class: 'text-blue-500 hover:text-blue-700 font-bold' %>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading flex justify-between items-center mb-4">
    <%= link_to t('simple_calendar.previous', default: '前週'), calendar.url_for_previous_view, class: 'text-blue-500 hover:text-blue-700 font-bold' %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: '1週間') %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: '1週間') %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: '翌週'), calendar.url_for_next_view, class: 'text-blue-500 hover:text-blue-700 font-bold' %>
    <% reservations = Reservation.reservations_after_three_month %>
  </div>
  <table class="w-full border-collapse border">
    <thead>
      <tr>
        <th>時間</th>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <td></td>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
        <% times.each do |time| %>
          <tr>
            <td><%= time %></td>
            <% week.each do |day| %>
              <td>

                <% if check_reservation(reservations, day, time) %>
                  <%= '-' %>
                <% else %>
                <%= link_to reservation_new_path(day: day, time: time), class: 'text-blue-500 hover:text-blue-700 font-bold' do %>
                  <%= '○' %>
                <% end %>
                  <% end %>

              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/static_pages/Contact.html.erb
<% provide(:title, "お問い合わせ") %>
<div>
  <h1 class="font-bold text-4xl">StaticPages#contact</h1>
  <p>Find me in app/views/static_pages/contact.html.erb</p>
</div>

app/views/static_pages/fee.html.erb
<% provide(:title, "料金") %>

<div class="min-h-screen flex flex-col">
        <div class="flex flex-col justify-center items-center max-w-screen-xl mx-auto mt-8">
            <h1 id="fee-title" class="text-7xl mt-20 mb-20">ー 料金 ー</h1>
                
              
                    <h3 id="fee-coment1" class="m-5 text-5xl font-bold border-b-4 border-black w-full">会員の方</h3>
                    <p id="fee-coment2" class="w-full text-3xl">月額：2,200円（税込）</p>
                    <p id="fee-coment2" class="w-full text-3xl">ジム利用：１時間利用ごとに500円（税込）</p>
                    <p id="fee-coment2" class="w-full text-3xl">パーソナルトレーニング：4,400円（税込）</p>
                    <p id="fee-coment2" class="w-full text-3xl mb-5">整体：4,400円（税込）</p>
                    <p id="fee-coment2" class="w-full text-3xl">・入会手数料：7,700円（入会費5,500円＋セキュリティー発行料2,200円がかかります。）</p>
                    <p id="fee-coment2" class="w-full text-3xl">18歳以下のご利用については、事前に親権の同意書が必要になります。</p>
  

                    <h3 id="fee-coment1" class="mt-20 mb-5 text-5xl font-bold border-b-4 border-black w-full">非会員の方</h3>
                    <p id="fee-coment2" class="w-full text-3xl">パーソナルレーニング：6,600円（税込）</p>
                    <p id="fee-coment2" class="w-full text-3xl mb-5">整体：6,600円（税込）</p>
                    <p id="fee-coment2" class="w-full text-3xl mb-32">・月額会員にならずに1回ごとのお支払いでご利用いただけます。</p>
                    

      
                
        </div>
    </div>

app/views/static_pages/service.html.erb
<% provide(:title, "サービス一覧") %>

<div class="min-h-screen flex flex-col justify-center items-center">
        <div class="flex flex-col justify-center items-center max-w-screen-xl mx-auto text-center mt-8">
            <h1 id="service-title" class="text-7xl mt-20 mb-20">ー サービス一覧 ー</h1>
                <div class="flex flex-col justify-center items-center">
                    <h3 class="m-5 text-4xl font-bold">ジム利用</h3>
                    <%= image_tag("adult-1850925_1280.jpg", class: "w-100 h-80") %>
                    <p id="service-coment" class="mt-5 font-bold text-3xl">
                        24時間営業のため、予約サイトからお好きな時間にご予約可能
                        ご予約時間は個室貸切りとなるため、周りの目を気にすることなく
                        ​トレーニングを行うことができます
                    </p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <h3 class="mt-16 mb-5 text-4xl font-bold">パーソナルトレーニング</h3>
                    <%= image_tag("woman-1730325_1280.jpg", class: "w-100 h-80") %>
                    <p id="service-coment" class="mt-5 font-bold text-3xl">
                        マンツーマンでトレーニングを指導
                        運動が初めての方や自分に合ったトレーニング方法を知り
                        ​より効果的で効率よく運動を行うことができます
                    </p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <h3 class="mt-16 mb-5 text-4xl font-bold">整体</h3>
                    <%= image_tag("massage-2768833_1280.jpg", class: "w-100 h-80") %>
                    <p id="service-coment" class="mt-5 font-bold text-3xl">
                        痛みの軽減や不調改善に最適
                        姿勢の歪みや凝り固まった筋肉による不調を改善し
                        ​運動を併用することで再発しない身体作りを目指します
                    </p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <h3 class="mt-16 mb-12 text-4xl font-bold">​オンライン食事指導</h3>
                    <%= image_tag("phone-869669_1280.jpg", class: "w-100 h-80") %>
                    <p id="service-coment" class="mt-5 font-bold text-3xl">
                        食事の管理によって身体作りの基本習慣を見直し
                        人間の身体は食事や運動の内容に大きな影響を受けます
                        食事面の改善が運動の効果を向上させ、健康的なライフスタイルへ
                        ​導くことができます
                    </p>
                </div>

                <p id="service-coment" class="mt-16 font-bold text-2xl text-red-500">※オプションメニュー、料金形態は担当スタッフにより異なる場合がございます。
                    詳細は以下のスタッフ紹介をご覧ください。
                </p>
                <button class="mt-5 mb-20 text-2xl bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                <%= link_to "スタッフの紹介はコチラ", 'staff' %>
                </button>
     

                <div class="max-w-screen-xl mx-auto text-center relative">
                <%= image_tag("dumbbell-1966247_1280.jpg", class: "w-full opacity-70 filter brightness-75") %>
                    <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-white w-full max-w-lg">
                        <h1 id="service-down-title" class="text-5xl mt-68 mb-14">今までにない新しい<br>フィットネスを体験しよう</h1>
                        <p id="service-down-coment" class="text-3xl font-bold my-5">さあ、今すぐフィットネスを始めよう‼︎</p>
                        <button id="service-button" class="m-20 text-4xl bg-yellow-300 hover:bg-yellow-400 text-black py-4 px-8 rounded-full">
                        <%= link_to "入会はこちら", 'signup' %>
                        </button>
                    </div>
                </div>
        </div>
    </div>

app/views/users/show.html.erb
<div class="flex flex-col mb-32">
  <div class="max-w-screen-xl mx-auto mt-8">
    <div class="flex flex-col justify-center items-center">

    <h1 id="mypage-title" class="text-7xl mt-20 mb-20">ー マイページ ー</h1>
    
      <h1 id="mypage_coment" class="text-2xl">名前: <%= @current_user.name %></h1>
      <h1 id="mypage_coment" class="text-2xl mb-20">メールアドレス: <%= @current_user.email %></h1>

      <h1 id="mypage_subtitle" class="text-5xl mb-10">予約一覧</h1>

      <% flash.each do |type, message| %>
        <div class="<%= type %>">
          <%= message %>
        </div>
      <% end %>

      <div class="col-12 mt-3 text-center mx-auto">
        <table class="w-full border-collapse border">
          <thead>
            <tr class="text-xl">
              <th scope="col" class="px-4 py-2">予約日</th>
              <th class="px-4 py-2"></th>
            </tr>
          </thead>
          <tbody>
            <% @user_reservations.each do |user_reservation| %>
              <tr>
                <td class="border px-4 py-2">
                  <%= user_reservation.day %>
                  <%= user_reservation.time %>          
                </td>
                <td class="border px-4 py-2">
                  <%= link_to "キャンセル", reservation_destroy_path(user_reservation.id), 
                              data: { "turbo-method": :delete },
                              onclick: "return confirm('本当にキャンセルしますか？')",
                              class: 'text-blue-500 hover:text-blue-700 font-bold' %>
                </td>
              </tr>
            <% end %>
            <% if @user_reservations.blank? %>
              <tr>
                <td class="border px-4 py-2" colspan="2">予約はありません。</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>